### PR TITLE
Upgraded Cake and implemented remaining FM args 

### PR DESCRIPTION
**Pull request by jjschlesinger**
Upgraded to Cake 0.15 and refactored to work with the updated API.

### CODE REVIEW

**Comment by jonathanstowell** [comment]
I assume this repository is no longer being maintained and that if we need to use Fluent Migrations with newer versions of Cake its required to fork and start a new nuget package?

**Comment by gep13** [comment]
>@jonathanstowell said...
I assume this repository is no longer being maintained and that if we need to use Fluent Migrations with newer versions of Cake its required to fork and start a new nuget package?

Ideally no, that is exactly what we (as the Cake team) don't want.  We think that duplicating packages, and having multiple forks of repositories, doesn't help the eco-system, and leads to confusion.  We actually wrote about this here:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

@FredrikL has already added the `cake-contrib` user as a co-maintainer of the Cake.FluentMigrator addin on NuGet.org, so we are in a position to push new package versions there, if we get to a point where that is required.  The @cake-build/team are in the process of reaching out to @FredrikL to see if we can move this repo to the cake-contrib organisation so that we can help with the maintenance of this project.  If/when that happens, we will be in a position to accept any additional contributions that might be required for this addin.

Please let me know if you have any questions about this.  Thanks!

**Comment by FredrikL** [comment]
@gep13 Hey, how should i transfer the repo to ?

For some reason i didn't get a notification about this pull request before..

**Comment by gep13** [comment]
@FredrikL assuming you are happy to move the repo to the `cake-contrib` organisation, if you could transfer ownership of this repo to me `gep13`, I can get it moved over to the `cake-contrib` organisation, and set up the necessary permissions, etc.

**Comment by FredrikL** [comment]
@gep13 Done!

**Comment by gep13** [comment]
>@FredrikL said...
@gep13 Done!

Thank you very much!  I appreciate your help in getting this resolved, and for creating the addin in the first instance!

**Comment by gep13** [comment]
@FredrikL As you will see, I have moved the repository into the Cake-Contrib Organisation, and I have invited you as a member of that Organisation, with full permissions on the repo.  That way, if you decide you want to, you can continue to maintain this addin.

@jjschlesinger are you in a position to update this PR to move to the latest version of Cake, i.e. v0.17.0?

If not, @jonathanstowell are you working on something that you could submit a PR for?

Failing that, I will look to get this addin updated to the latest version of Cake tonight, and get a new version pushed to NuGet.org.

Thanks

**Comment by jonathanstowell** [comment]
@gep13 I actually cloned @jjschlesinger repository, built it locally and reference the assembly directly using #r which I assume gives roslyn an instruction to load that lib.

It would be good to get the pull request into this repo and then move it to the Cake-Contrib organisation so we can maintain it as a community.

**Comment by gep13** [comment]
>@jonathanstowell said...
built it locally and reference the assembly directly using #r which I assume gives roslyn an instruction to load that lib.

That is correct, yes.

>@jonathanstowell said...
It would be good to get the pull request into this repo and then move it to the Cake-Contrib organisation so we can maintain it as a community.

This is certainly the plan, yes.  This repo is now already in the cake-contrib organisation, and all the Cake Team Members and @FredrikL have commit access to the repo.  If you are wanting to help maintain the project in a more official capacity, and @FredrikL has no objections, then I can certainly add you as a member of the repo.

**Comment by FredrikL** [comment]
If someone else wants to maintain it i'm all for it, i don't work in the .net ecosystem at the moment so my need (and time) for this kind of tool is rather low at the moment

**Comment by jjschlesinger** [comment]
I have updated this pull request. I upgraded the cake reference to 0.17.

**Comment by gep13** [comment]
@jjschlesinger thanks for getting that updated!  Really appreciate it!

@jonathanstowell @FredrikL I have merged, and published a new release of Cake.FluentMigrator.  You can find it here:

https://www.nuget.org/packages/Cake.FluentMigrator/0.2.0

Can you please give it a try, and let me know if you run into any issues.  Thanks!

**Comment by jjschlesinger** [comment]
I was able to test, and it looks like everything is behaving the way it should.

**Comment by gep13** [comment]
>@jjschlesinger said...
I was able to test, and it looks like everything is behaving the way it should.

Nice one! Thank you for taking it for a spin!

**Pull request merged**
